id: AB1A7C42C
title: 'The Swift Infusion of Blessings: A Guru Yoga of the Great Embodiment of Unchanging
  Awareness Wisdom'
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:44:01.923049
  last_modified_at: 2022-03-01 03:44:01.923052
