id: AB1A7C42C
title: The Swift Accomplishment of Enlightened Activity through Invocation and Offering
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:44:01.919598
  last_modified_at: 2022-03-01 03:44:01.919601
