id: AB1A7C42C
title: Brief Gesar Windhorse Invocation
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:44:01.901527
  last_modified_at: 2022-03-01 03:44:01.901533
