id: AB1A7C42C
title: Brief Smoke Offering to the Great Lion of the World
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:44:01.906211
  last_modified_at: 2022-03-01 03:44:01.906214
