id: AB1A7C42C
title: 'The Spontaneous Fulfilment of Wishes: A Daily Prayer to Gesar, King of the
  Dralas'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:44:01.918422
  last_modified_at: 2022-03-01 03:44:01.918426
