id: AB1A7C42C
title: Petitionary Offering to Norbu Dradül Tsal
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:44:01.909722
  last_modified_at: 2022-03-01 03:44:01.909725
