id: AB1A7C42C
title: Great Clouds of First-Portion Offerings for Prosperity
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:44:01.908416
  last_modified_at: 2022-03-01 03:44:01.908419
